### ISSUE TITLE
Graphics for webpage

### ISSUE THREAD

**Issue by bonimy** [catwise/catwise.github.io#2]
@petereisenhardt would like to add some graphics to the webpage if possible. He mentioned that @acertainelijah did a CatWISE presentation that had some graphics that may be usable here.

**Comment by petereisenhardt** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/30329025/57260844-445e4480-701a-11e9-9bee-46d8de637262.png">

Banner ac ross the top of the CatWISE data page

**Comment by petereisenhardt** [comment]
<img width="169" alt="image" src="https://user-images.githubusercontent.com/30329025/57260967-ba62ab80-701a-11e9-9a2e-b3cc0a3f31ab.png">

AllWISE sky coverage

**Comment by petereisenhardt** [comment]
<img width="172" alt="image" src="https://user-images.githubusercontent.com/30329025/57260995-dc5c2e00-701a-11e9-9018-24fb14ed2fa5.png">

CatWISE sky coverage

**Comment by petereisenhardt** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/30329025/57261253-f21e2300-701b-11e9-86fb-4265d0498396.png">

Comparison of AllWISE and CatWISE astrometric performance

**Comment by petereisenhardt** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/30329025/57414094-a8fcd900-71ab-11e9-9142-889963850df0.png">

Thinner banner for web page

**Comment by petereisenhardt** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/30329025/57420204-62af7600-71bb-11e9-83f8-6888ba4edae4.png">

Even thinner banner

**Comment by bonimy** [comment]
@petereisenhardt There's whitespace left in the image.

**Comment by petereisenhardt** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/30329025/57420897-701a2f80-71be-11e9-9669-f468550885b1.png">

Still thinner

**Comment by petereisenhardt** [comment]
![CatWISEvsAllWISE_Gaia](https://user-images.githubusercontent.com/30329025/57659897-e3de8280-7598-11e9-80a7-99bcae48b469.png)

Improved version of CatWISE vs AllWISE figure

**Comment by petereisenhardt** [comment]
![CatWISEvsAllWISE_Phot_z](https://user-images.githubusercontent.com/30329025/57660341-02457d80-759b-11e9-9480-20720dc8523f.png)

Another graphic for the CatWISE gallery

**Comment by bonimy** [comment]
Closing now that webpage is live.
